const products = [
  {
    id: 0,
    name: "SAMSUNG GALAXY A25 8GB/256GB",
    price: "₵ 4,799.00",
    description: "",
    category: "phones",
    image: "/images/laptop.webp",
  },
  {
    id: 1,
    name: "Product 2",
    price: "40.00",
    description: "This is product 2",
    category: "product2",
    image: "/images/laptop.webp",
  },
  {
    id: 2,
    name: "Product 3",
    price: "10.00",
    description: "This is product 3",
    category: "product3",
    image: "/images/laptop.webp",
  },
  {
    id: 3,
    name: "Product 4",
    price: "20.00",
    description: "This is product 4",
    category: "product4",
    image: "/images/laptop.webp",
  },
  {
    id: 4,
    name: "Product 5",
    price: "90.00",
    description: "This is product 5",
    category: "product5",
    image: "/images/laptop.webp",
  },
  {
    id: 5,
    name: "Product 6",
    price: "30.00",
    description: "This is product 6",
    category: "product6",
    image: "/images/laptop.webp",
  },
];
